branch-defaults:
  code:
    environment: movie-rating
    group_suffix: null
global:
  application_name: movie-rating
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python-2.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
